#title: Evolucion del COVID-19 en el Peru
author: AgustinTapia 
email: a.tapia245@gmail.com
#description: >
#  Insights sobre la pandemia en el Peru.

# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
