title: EVOLUCIÓN DEL COVID-19 EN EL PERÚ
author: AgustinTapia 
email: a.tapia245@gmail.com
description: >
  Insights sobre la pandemia COVID-19 en el Perú.

# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-midnight

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # can be pages, posts or drafts
    values:
      layout: "default"
